# The following three options specify
# a madlibs-style description of yourself.
# I ____________  at ____________________.
# I like ________________________________.
# No need for periods, we'll add them :)

I: 
at: Coderbase.io
I like: 

# Add your twitter handle to display your most 
# recent tweet and link to your twitter account.
# Your twitter account is the only contact information 
# visible to the public.

Twitter: 